### ISSUE TITLE
update build.py

### ISSUE THREAD

**Issue by claudioccm** [GovLab/academy-website#1]
# What we need:
- to generate one html file for each item in the 'data/project-gallery.yaml' file. 
  These html files should be generated from the 'templates/project.html' file.
# What would be cool to have:
- have a build.py file similar to what we have for the website, with a better organized code, running server and sass within the build, and also running that cleanup() function from the website build.py
- IMO, the website => build.py is better organized and easier to understand, and ideally we could streamline all our build.py files into basic structure file.
- it would be good to generate all the project html files inside a '/projects' folder, for organization purposes
- I don't really see a reason to store base.html inside the layout folder. we could get rid of it. Makes no sense for me
# Workflow bug
- when I'm working on base.html, I need to constantly re-run the build command, otherwise the build doesn't work. I don't know if this is a jinja limitation or something we could fix in the build.py file.

**Comment by toolness** [comment]
Ok, everything not related to the project gallery in this issue has been fixed by #3, while all the project gallery related items are covered by #2, so I'm closing this issue.

**Comment by claudioccm** [comment]
Perfect. Sorry for the duplication
